apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-resolver-deployment
  labels:
    app: uni-resolver    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uni-resolver
  template:
    metadata:
      labels:
        app: uni-resolver
    spec:
      containers:
      - name: uni-resolver-container
        image:  universalresolver/uni-resolver-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: uniresolver_web_driver_url_did_btcr
          value: ""
          
          
