apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uni-resolver-tls
  namespace: uni-resolver
  annotations:
    cert-manager.io/issuer-kind: "ClusterIssuer"
    cert-manager.io/issuer-name: "letsencrypt-prod" 
spec:
  dnsNames:
    - universal-did-resolver.1edtech.org
  secretName: universal-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer