apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-app
  namespace: default
spec:
  dnsNames:
    - universal-did-resolver.1edtech.org
  secretName: universal-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer