apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    cert-manager.io/ignore-webhook-validation: "true"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: rfeidangai@1edtech.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx     